In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
from tqdm import tqdm
corpus = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/data/음식점_train.csv')
corpus

IDX 발화자                               발화문 카테고리   QA번호 QA여부 감성  \
0            1   c             참치타다끼샐러드는 취소했었는데, 맞죠?  음식점  32365    q  m   
1            2   s           네, 참치타다끼샐러드는 취소된 상태입니다.  음식점  32365    a  m   
2            3   c  주문한 메뉴 취소할 때 주문서만 있으면 된다는 말씀이세요?  음식점  15016    q  m   
3            4   s             네, 주문서만 있으면 취소 가능합니다.  음식점  15016    a  m   
4            5   c             고객서비스가 엉망이군요. 그냥 갑니다.  음식점  62984    q  n   
...        ...  ..                               ...  ...    ...  ... ..   
290382  290383   s        성북동까지 지금 시간에는 40분 이상 걸립니다.  음식점  50614    a  m   
290383  290384   c         짜장면 지금 주문하면 바로 배달 올 수 있죠?  음식점  18579    q  m   
290384  290385   s            네, 지금 주문하시면 바로 배달 갑니다.  음식점  18579    a  m   
290385  290386   c    롯데유치원에 피자 20판 보내야하는데 5시까지 될까요?  음식점  59570    q  m   
290386  290387   s       네, 피자 20판 5시까지 보내드릴 수 있습니다.  음식점  59570    a  m   

             인텐트   가격   수량   크기     장소   조직   사람   시간   날짜       상품명   상담번호  \
0       주문_취소_확인  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  참치타다끼샐러드  32365   
1       주문_취소_확인  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  참치타다끼샐러드  32365   
2       주문_취소_확인  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN       NaN  15016   
3       주문_취소_확인  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN       NaN  15016   
4       주문_취소_확인  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN       NaN  62984   
...          ...  ...  ...  ...    ...  ...  ...  ...  ...       ...    ...   
290382  배송_날짜_요청  NaN  NaN  NaN    성북동  NaN  NaN  NaN  NaN       NaN  50614   
290383  배송_날짜_요청  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN       짜장면  18579   
290384  배송_날짜_요청  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN       NaN  18579   
290385  배송_날짜_요청  NaN  NaN  NaN  롯데유치원  NaN  NaN   5시  NaN        피자  59570   
290386  배송_날짜_요청  NaN  NaN  NaN    NaN  NaN  NaN   5시  NaN        피자  59570   

        상담내순번  
0           1  
1           2  
2           1  
3           2  
4           1  
...       ...  
290382      2  
290383      1  
290384      2  
290385      1  
290386      2  

[290387 rows x 19 columns]

In [3]:
Q = []
A = []
flag = 0
for i in tqdm(range(len(corpus))):
  if flag > i :
    pass
  else :
    if corpus.iloc[i]['QA여부'] == 'q':
      list_q = []
      list_q.append(corpus.iloc[i]['발화문'])
      for j in range(i+1, len(corpus)):
        if corpus.iloc[j]['QA여부'] == 'a':
          flag = j
        if flag == j:
          break
        else : 
          list_q.append(corpus.iloc[j]['발화문'])
      Q.append(' '.join(list_q))
    else :
      list_a = []
      list_a.append(corpus.iloc[i]['발화문'])
      for j in range(i+1, i+50):
        try : 
          if corpus.iloc[j]['QA여부'] == 'q':
            flag = j

          if flag == j:
            break
          else : 
            list_a.append(corpus.iloc[j]['발화문'])
        except :
          pass
      A.append(' '.join(list_a))

100%|██████████| 290387/290387 [01:29<00:00, 3253.55it/s]


In [4]:
corpus = pd.DataFrame({'Q':Q,
                           'A':A})
corpus

Q  \
0                           참치타다끼샐러드는 취소했었는데, 맞죠?   
1                주문한 메뉴 취소할 때 주문서만 있으면 된다는 말씀이세요?   
2                           고객서비스가 엉망이군요. 그냥 갑니다.   
3                 방금 전에 홍합탕 주문한 거 지금 취소 가능한 거 맞죠?   
4       매운무뼈닭발 롯데주유소로 주문한 거 아직 안받았는데, 취소해도 되는 거죠?   
...                                           ...   
119372      짜장면 12:30까지 배달되야 먹는데 그 시간까지 오실 수 있나요?   
119373             후라이드 5마리 시킨 곳인데 배달 출발한 거 확실해요?   
119374             성북동까지 치킨 배달시키면 얼마나 걸리는지 알려주세요.   
119375                  짜장면 지금 주문하면 바로 배달 올 수 있죠?   
119376             롯데유치원에 피자 20판 보내야하는데 5시까지 될까요?   

                                       A  
0                네, 참치타다끼샐러드는 취소된 상태입니다.  
1                  네, 주문서만 있으면 취소 가능합니다.  
2                원하시는 서비스를 제공하지못해 죄송합니다.  
3       네, 주문하신 홍합탕은 아직 조리 전이라 취소 가능합니다.  
4        아니요, 이미 접수 후 조리 시작하여 취소는 어렵습니다.  
...                                  ...  
119372            네, 말씀하신 시간까지 배달해 드릴게요.  
119373     네, 배달 출발한 건지 알아 보고 연락 드리겠습니다.  
119374        성북동까지 지금 시간에는 40분 이상 걸립니다.  
119375            네, 지금 주문하시면 바로 배달 갑니다.  
119376       네, 피자 20판 5시까지 보내드릴 수 있습니다.  

[119377 rows x 2 columns]

In [5]:
corpus = corpus[corpus['A'] != '네'][corpus['A'] != '네.']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [6]:
from tensorflow import keras
from keras import models
from keras import layers
from keras import optimizers, losses, metrics
from keras import preprocessing

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import os
import re
!pip install konlpy
from konlpy.tag import Okt

In [7]:
# 태그 단어
PAD = "<PADDING>"   # 패딩
STA = "<START>"     # 시작
END = "<END>"       # 끝
OOV = "<OOV>"       # 없는 단어(Out of Vocabulary)

# 태그 인덱스
PAD_INDEX = 0
STA_INDEX = 1
END_INDEX = 2
OOV_INDEX = 3

# 데이터 타입
ENCODER_INPUT  = 0
DECODER_INPUT  = 1
DECODER_TARGET = 2

# 한 문장에서 단어 시퀀스의 최대 개수
max_sequences = 30

# 임베딩 벡터 차원
embedding_dim = 100

# LSTM 히든레이어 차원
lstm_hidden_dim = 128

# 정규 표현식 필터
RE_FILTER = re.compile("[.,!?\"':;~()]")

# 챗봇 데이터 로드
question, answer = list(corpus['Q']), list(corpus['A'])

In [8]:
# 데이터의 일부만 학습에 사용
question = question[:5000]
answer = answer[:5000]

# 챗봇 데이터 출력
for i in range(10):
    print('Q : ' + question[i])
    print('A : ' + answer[i])
    print()

Q : 참치타다끼샐러드는 취소했었는데, 맞죠?
A : 네, 참치타다끼샐러드는 취소된 상태입니다.

Q : 주문한 메뉴 취소할 때 주문서만 있으면 된다는 말씀이세요?
A : 네, 주문서만 있으면 취소 가능합니다.

Q : 고객서비스가 엉망이군요. 그냥 갑니다.
A : 원하시는 서비스를 제공하지못해 죄송합니다.

Q : 방금 전에 홍합탕 주문한 거 지금 취소 가능한 거 맞죠?
A : 네, 주문하신 홍합탕은 아직 조리 전이라 취소 가능합니다.

Q : 매운무뼈닭발 롯데주유소로 주문한 거 아직 안받았는데, 취소해도 되는 거죠?
A : 아니요, 이미 접수 후 조리 시작하여 취소는 어렵습니다.

Q : 주문한걸 취소하려면 주문서가 필요한거죠?
A : 네, 맞습니다 주문서가 필요합니다. 

Q : 멸치볶음만 취소할 수 있죠?
A : 네, 멸치볶음만 취소할 수 있습니다.

Q : 롯데주유소로 매운무뼈닭발 주문한 거 아직 안받았는데, 취소해도 되는 거죠?
A : 네, 현재 접수단계로 주문 취소 가능합니다.

Q : 주문서만 있으면 취소가 된다는거에요?
A : 네, 주문서만 있으면 취소가 됩니다.

Q : 순두부백반 취소된 거 맞죠?
A : 네, 순두부백반 취소되었습니다.



In [9]:
# 형태소분석 함수
def pos_tag(sentences):
    
    # KoNLPy 형태소분석기 설정
    tagger = Okt()
    
    # 문장 품사 변수 초기화
    sentences_pos = []
    
    # 모든 문장 반복
    for sentence in sentences:
        # 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        
        # 배열인 형태소분석의 출력을 띄어쓰기로 구분하여 붙임
        sentence = " ".join(tagger.morphs(sentence))
        sentences_pos.append(sentence)
        
    return sentences_pos

In [10]:
# 형태소분석 수행
question = pos_tag(question)
answer = pos_tag(answer)

# 형태소분석으로 변환된 챗봇 데이터 출력
for i in range(10):
    print('Q : ' + question[i])
    print('A : ' + answer[i])
    print()

Q : 참치 타다 끼 샐러드 는 취소 했었는데 맞죠
A : 네 참치 타다 끼 샐러드 는 취소 된 상태 입니다

Q : 주문 한 메뉴 취소 할 때 주 문서 만 있으면 된다는 말씀 이세 요
A : 네 주 문서 만 있으면 취소 가능합니다

Q : 고객 서비스 가 엉망 이군 요 그냥 갑니다
A : 원하시는 서비스 를 제공 하지못해 죄송합니다

Q : 방금 전 에 홍합 탕 주문 한 거 지금 취소 가능한 거 맞죠
A : 네 주문 하신 홍합 탕 은 아직 조리 전이 라 취소 가능합니다

Q : 매 운무 뼈 닭발 롯데 주유소 로 주문 한 거 아직 안 받았는데 취소 해도 되는 거 죠
A : 아니요 이미 접수 후 조리 시작 하여 취소 는 어렵습니다

Q : 주 문 한 걸 취소 하려면 주 문서 가 필요한거죠
A : 네 맞습니다 주 문서 가 필요합니다

Q : 멸치 볶음 만 취소 할 수 있죠
A : 네 멸치 볶음 만 취소 할 수 있습니다

Q : 롯데 주유소 로 매 운무 뼈 닭발 주문 한 거 아직 안 받았는데 취소 해도 되는 거 죠
A : 네 현재 접수 단계 로 주문 취소 가능합니다

Q : 주 문서 만 있으면 취소 가 된다는거에요
A : 네 주 문서 만 있으면 취소 가 됩니다

Q : 순두부 백반 취소 된 거 맞죠
A : 네 순두부 백반 취소 되었습니다



In [11]:
# 질문과 대답 문장들을 하나로 합침
sentences = []
sentences.extend(question)
sentences.extend(answer)

words = []

# 단어들의 배열 생성
for sentence in sentences:
    for word in sentence.split():
        words.append(word)

# 길이가 0인 단어는 삭제
words = [word for word in words if len(word) > 0]

# 중복된 단어 삭제
words = list(set(words))

# 제일 앞에 태그 단어 삽입
words[:0] = [PAD, STA, END, OOV]

In [12]:
# 단어와 인덱스의 딕셔너리 생성
word_to_index = {word: index for index, word in enumerate(words)}
index_to_word = {index: word for index, word in enumerate(words)}

In [13]:
# 문장을 인덱스로 변환
def convert_text_to_index(sentences, vocabulary, type): 
    
    sentences_index = []
    
    # 모든 문장에 대해서 반복
    for sentence in sentences:
        sentence_index = []
        
        # 디코더 입력일 경우 맨 앞에 START 태그 추가
        if type == DECODER_INPUT:
            sentence_index.extend([vocabulary[STA]])
        
        # 문장의 단어들을 띄어쓰기로 분리
        for word in sentence.split():
            if vocabulary.get(word) is not None:
                # 사전에 있는 단어면 해당 인덱스를 추가
                sentence_index.extend([vocabulary[word]])
            else:
                # 사전에 없는 단어면 OOV 인덱스를 추가
                sentence_index.extend([vocabulary[OOV]])

        # 최대 길이 검사
        if type == DECODER_TARGET:
            # 디코더 목표일 경우 맨 뒤에 END 태그 추가
            if len(sentence_index) >= max_sequences:
                sentence_index = sentence_index[:max_sequences-1] + [vocabulary[END]]
            else:
                sentence_index += [vocabulary[END]]
        else:
            if len(sentence_index) > max_sequences:
                sentence_index = sentence_index[:max_sequences]
            
        # 최대 길이에 없는 공간은 패딩 인덱스로 채움
        sentence_index += (max_sequences - len(sentence_index)) * [vocabulary[PAD]]
        
        # 문장의 인덱스 배열을 추가
        sentences_index.append(sentence_index)

    return np.asarray(sentences_index)

In [14]:
# 인코더 입력 인덱스 변환
x_encoder = convert_text_to_index(question, word_to_index, ENCODER_INPUT)

# 첫 번째 인코더 입력 출력 (12시 땡)
x_encoder[0]

array([4404,  973, 3826,  776, 2528,  168,  516, 4317,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [15]:
# 디코더 입력 인덱스 변환
x_decoder = convert_text_to_index(answer, word_to_index, DECODER_INPUT)

# 첫 번째 디코더 입력 출력 (START 하루 가 또 가네요)
x_decoder[0]

array([   1, 1316, 4404,  973, 3826,  776, 2528,  168, 3753,  378, 2779,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [16]:
# 디코더 목표 인덱스 변환
y_decoder = convert_text_to_index(answer, word_to_index, DECODER_TARGET)

# 첫 번째 디코더 목표 출력 (하루 가 또 가네요 END)
y_decoder[0]

array([1316, 4404,  973, 3826,  776, 2528,  168, 3753,  378, 2779,    2,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0])

In [17]:
# 원핫인코딩 초기화
one_hot_data = np.zeros((len(y_decoder), max_sequences, len(words)))

# 디코더 목표를 원핫인코딩으로 변환
# 학습시 입력은 인덱스이지만, 출력은 원핫인코딩 형식임
for i, sequence in enumerate(y_decoder):
    for j, index in enumerate(sequence):
        one_hot_data[i, j, index] = 1

# 디코더 목표 설정
y_decoder = one_hot_data

# 첫 번째 디코더 목표 출력
y_decoder[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [18]:
#--------------------------------------------
# 훈련 모델 인코더 정의
#--------------------------------------------

# 입력 문장의 인덱스 시퀀스를 입력으로 받음
encoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
encoder_outputs = layers.Embedding(len(words), embedding_dim)(encoder_inputs)

# return_state가 True면 상태값 리턴
# LSTM은 state_h(hidden state)와 state_c(cell state) 2개의 상태 존재
encoder_outputs, state_h, state_c = layers.LSTM(lstm_hidden_dim,
                                                dropout=0.1,
                                                recurrent_dropout=0.5,
                                                return_state=True)(encoder_outputs)

# 히든 상태와 셀 상태를 하나로 묶음
encoder_states = [state_h, state_c]



#--------------------------------------------
# 훈련 모델 디코더 정의
#--------------------------------------------

# 목표 문장의 인덱스 시퀀스를 입력으로 받음
decoder_inputs = layers.Input(shape=(None,))

# 임베딩 레이어
decoder_embedding = layers.Embedding(len(words), embedding_dim)
decoder_outputs = decoder_embedding(decoder_inputs)

# 인코더와 달리 return_sequences를 True로 설정하여 모든 타임 스텝 출력값 리턴
# 모든 타임 스텝의 출력값들을 다음 레이어의 Dense()로 처리하기 위함
decoder_lstm = layers.LSTM(lstm_hidden_dim,
                           dropout=0.1,
                           recurrent_dropout=0.5,
                           return_state=True,
                           return_sequences=True)

# initial_state를 인코더의 상태로 초기화
decoder_outputs, _, _ = decoder_lstm(decoder_outputs,
                                     initial_state=encoder_states)

# 단어의 개수만큼 노드의 개수를 설정하여 원핫 형식으로 각 단어 인덱스를 출력
decoder_dense = layers.Dense(len(words), activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)



#--------------------------------------------
# 훈련 모델 정의
#--------------------------------------------

# 입력과 출력으로 함수형 API 모델 생성
model = models.Model([encoder_inputs, decoder_inputs], decoder_outputs)

# 학습 방법 설정
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['acc'])    

In [19]:
#--------------------------------------------
#  예측 모델 인코더 정의
#--------------------------------------------

# 훈련 모델의 인코더 상태를 사용하여 예측 모델 인코더 설정
encoder_model = models.Model(encoder_inputs, encoder_states)



#--------------------------------------------
# 예측 모델 디코더 정의
#--------------------------------------------

# 예측시에는 훈련시와 달리 타임 스텝을 한 단계씩 수행
# 매번 이전 디코더 상태를 입력으로 받아서 새로 설정
decoder_state_input_h = layers.Input(shape=(lstm_hidden_dim,))
decoder_state_input_c = layers.Input(shape=(lstm_hidden_dim,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]    

# 임베딩 레이어
decoder_outputs = decoder_embedding(decoder_inputs)

# LSTM 레이어
decoder_outputs, state_h, state_c = decoder_lstm(decoder_outputs,
                                                 initial_state=decoder_states_inputs)

# 히든 상태와 셀 상태를 하나로 묶음
decoder_states = [state_h, state_c]

# Dense 레이어를 통해 원핫 형식으로 각 단어 인덱스를 출력
decoder_outputs = decoder_dense(decoder_outputs)

# 예측 모델 디코더 설정
decoder_model = models.Model([decoder_inputs] + decoder_states_inputs,
                      [decoder_outputs] + decoder_states)

In [20]:
# 인덱스를 문장으로 변환
def convert_index_to_text(indexs, vocabulary): 
    
    sentence = ''
    
    # 모든 문장에 대해서 반복
    for index in indexs:
        if index == END_INDEX:
            # 종료 인덱스면 중지
            break;
        elif vocabulary.get(index) is not None:
            # 사전에 있는 인덱스면 해당 단어를 추가
            sentence += vocabulary[index]
        else:
            # 사전에 없는 인덱스면 OOV 단어를 추가
            sentence += vocabulary[OOV_INDEX]
            
        # 빈칸 추가
        sentence += ' '

    return sentence

In [ ]:
# 에폭 반복
for epoch in range(10):
    print('Total Epoch :', epoch + 1)

    # 훈련 시작
    history = model.fit([x_encoder, x_decoder],
                        y_decoder,
                        epochs=30,
                        batch_size=64,
                        verbose=0)
    
    # 정확도와 손실 출력
    print('accuracy :', history.history['acc'][-1])
    print('loss :', history.history['loss'][-1])
    
    # 문장 예측 테스트
    # (3 박 4일 놀러 가고 싶다) -> (여행 은 언제나 좋죠)
    input_encoder = x_encoder[2].reshape(1, x_encoder[2].shape[0])
    input_decoder = x_decoder[2].reshape(1, x_decoder[2].shape[0])
    results = model.predict([input_encoder, input_decoder])
    
    # 결과의 원핫인코딩 형식을 인덱스로 변환
    # 1축을 기준으로 가장 높은 값의 위치를 구함
    indexs = np.argmax(results[0], 1) 
    
    # 인덱스를 문장으로 변환
    sentence = convert_index_to_text(indexs, index_to_word)
    print(sentence)
    print()

Total Epoch : 1


In [22]:
# 모델 저장
encoder_model.save('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/model/encoder.h5')
decoder_model.save('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/model/decoder.h5')

# 인덱스 저장
with open('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/tokenizer/word_index.pkl', 'wb') as f:
    pickle.dump(word_to_index, f, pickle.HIGHEST_PROTOCOL)
with open('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/tokenizer/index_to_word.pkl', 'wb') as f:
    pickle.dump(index_to_word, f, pickle.HIGHEST_PROTOCOL)    

In [23]:
# 모델 파일 로드
encoder_model2 = models.load_model('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/model/encoder.h5')
decoder_model2 = models.load_model('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/model/decoder.h5')

# 인덱스 파일 로드
with open('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/tokenizer/word_index.pkl', 'rb') as f:
    word_to_index = pickle.load(f)
with open('/content/drive/MyDrive/Colab Notebooks/ssac/nlp/tokenizer/index_to_word.pkl', 'rb') as f:
    index_to_word = pickle.load(f)   

In [24]:
# 예측을 위한 입력 생성
def make_predict_input(sentence):

    sentences = []
    sentences.append(sentence)
    sentences = pos_tag(sentences)
    input_seq = convert_text_to_index(sentences, word_to_index, ENCODER_INPUT)
    
    return input_seq

In [25]:
# 텍스트 생성
def generate_text(input_seq):
    
    # 입력을 인코더에 넣어 마지막 상태 구함
    states = encoder_model2.predict(input_seq)

    # 목표 시퀀스 초기화
    target_seq = np.zeros((1, 1))
    
    # 목표 시퀀스의 첫 번째에 <START> 태그 추가
    target_seq[0, 0] = STA_INDEX
    
    # 인덱스 초기화
    indexs = []
    
    # 디코더 타임 스텝 반복
    while 1:
        # 디코더로 현재 타임 스텝 출력 구함
        # 처음에는 인코더 상태를, 다음부터 이전 디코더 상태로 초기화
        decoder_outputs, state_h, state_c = decoder_model2.predict(
                                                [target_seq] + states)

        # 결과의 원핫인코딩 형식을 인덱스로 변환
        index = np.argmax(decoder_outputs[0, 0, :])
        indexs.append(index)
        
        # 종료 검사
        if index == END_INDEX or len(indexs) >= max_sequences:
            break

        # 목표 시퀀스를 바로 이전의 출력으로 설정
        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = index
        
        # 디코더의 이전 상태를 다음 디코더 예측에 사용
        states = [state_h, state_c]

    # 인덱스를 문장으로 변환
    sentence = convert_index_to_text(indexs, index_to_word)
        
    return sentence

In [27]:
generate_text(make_predict_input('문래동까지 배달이 얼마나 걸리나요?'))

'배달 비는 3000원 입니다 '